In [1]:
import gym
import random
import numpy as np

env = gym.make("MountainCar-v0")
env.reset()

print(env.observation_space.high)
print(env.observation_space.low)
print(env.action_space.n)

discrete_os_size = [20]*len(env.observation_space.high)
discrete_os_win_size = (env.observation_space.high-env.observation_space.low)/discrete_os_size
print(discrete_os_win_size)

q_table = np.random.uniform(low=-2,high=0,size=(discrete_os_size+[env.action_space.n])) 
print(q_table.shape)
print(q_table)

"""
done = False
while not False:
    action = random.choice([0,2])
    new_state, reward,done,_ = env.step(action)
    print('Action: '+str(action)+' New state: '+str(new_state)+' Reward: '+str(reward)+' Done: '+str(done))
    env.render()
    
env.close()
"""

[0.6  0.07]
[-1.2  -0.07]
3
[0.09  0.007]
(20, 20, 3)
[[[-1.55868894 -0.05171415 -0.83014167]
  [-0.20215692 -0.19860144 -0.78428411]
  [-1.83989814 -0.34695395 -1.75254026]
  ...
  [-1.01260973 -1.8708665  -1.30892221]
  [-1.29704195 -0.55888491 -1.5523499 ]
  [-0.65798788 -1.46842415 -1.57359657]]

 [[-1.45970989 -0.21372961 -0.52525456]
  [-0.16014813 -1.77052985 -1.20086918]
  [-1.40153947 -0.42911074 -1.51536577]
  ...
  [-0.30234171 -0.051642   -0.10365527]
  [-0.4022853  -1.84084803 -0.65942658]
  [-0.76324819 -0.82730454 -0.32474173]]

 [[-0.60778553 -0.34979741 -0.34909125]
  [-0.00672739 -1.83156407 -0.56619033]
  [-1.52535605 -1.94457336 -0.56904439]
  ...
  [-1.86468346 -0.09350739 -1.26219108]
  [-0.86274173 -1.97320615 -1.73222871]
  [-0.21540343 -1.44748368 -0.47176068]]

 ...

 [[-1.1328898  -0.03278651 -0.61668235]
  [-1.10584371 -0.12497639 -1.7934716 ]
  [-1.757846   -1.79284069 -0.2954655 ]
  ...
  [-1.00824154 -1.22680526 -0.15409556]
  [-1.09616814 -0.73337169 -1.

"\ndone = False\nwhile not False:\n    action = random.choice([0,2])\n    new_state, reward,done,_ = env.step(action)\n    print('Action: '+str(action)+' New state: '+str(new_state)+' Reward: '+str(reward)+' Done: '+str(done))\n    env.render()\n    \nenv.close()\n"